export const becarias = [
    {
         id: 13519912412,
         name: "Mariana Agustina",
         surname: "Etchegaray",
         carreer: ["Licenciatura en Informatica"],
         city: "La Plata",
         address: "Suipacha 312",
         dni: 15324532,
         email: "jsmand@gmail.com",
         actualState: "Aprobada",
         birthday: "1994-12-12",
         urlPhoto: "algunaURLdeImagen",
         country: "Argentina",
         province: "Buenos Aires",
         telephone: "1278945632",
         tutor: {objetoTutor} no editable,
         documentation: [Strings],
         activities:[activitiesID],
         accountID: cuentaID,
        },
        {
             id: 13519912412,
             name: "Mariana Agustina",
             surname: "Etchegaray",
             carreer: ["Licenciatura en Informatica"],
             city: "La Plata",
             address: "Suipacha 312",
             dni: 15324532,
             email: "jsmand@gmail.com",
             actualState: "Aprobada",
             birthday: "1994-12-12",
             urlPhoto: "algunaURLdeImagen",
             country: "Argentina",
             province: "Buenos Aires",
             telephone: "1278945632",
             tutor: {objetoTutor} no editable,
             documentation: [Strings],
             activities:[activitiesID],
             accountID: cuentaID,
            }
]
